site_name: Breakout Docs

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      repos:
        - section: Test Actions
          import_url: https://github.com/bmarcosps/test-actions?branch={dev}

theme:
  name: material
