site_name: Breakout Docs

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      repos:
        - section: Test Actions
          import_url: git@github.com:{bmarcosps}/{test-actions}.git?branch={dev}
        - section: Simple API
          import_url: git@github.com:{bmarcosps}/{simple-api}.git?branch={simple-typescript}

theme:
  name: material
