site_name: Breakout Docs

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      repos:
        - section: Test Actions
          import_url: https://github.com/bmarcosps/test-actions.git?branch=dev
        - section: Simple API
          import_url: https://github.com/bmarcosps/simple-api.git?branch=simple-typescript

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: blue
      accent: blue
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: blue
      accent: blue
