name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: bmarcosps/actions-mkdocs@v0.1
        with:
          mkdocs_version: 'latest' # option
          requirements: 'requirements.txt' # option
          configfile: 'mkdocs.yml' # option
      - name: Print
        run: |
          ls -la
          cd site
          ls -la
          cd ..
          cd ..
          ls -la
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
