name: Deploy

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AccessToken: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.13'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build site
        run: |
          mkdocs build
      - name: Print
        run: |
          ls -la
          cd site
          ls -la
          cd ..
          cd docs
          ls -la
          cd ..
          cd ..
          ls -la

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
#  - name: Print Before
#         run: |
#           ls -la
#           cd docs
#           ls -la
#           cd ..
#           cd ..
#           ls -la
#       - name: Build
#         uses: bmarcosps/actions-mkdocs@v0.2
#         with:
#           mkdocs_version: 'latest' # option
#           requirements: 'requirements.txt' # option
#           configfile: 'mkdocs.yml' # option
#       - name: Print
#         run: |
#           ls -la
#           cd site
#           ls -la
#           cd ..
#           cd docs
#           ls -la
#           cd ..
#           cd ..
#           ls -la
