name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          requirements: 'requirements.txt' # option
          configfile: 'mkdocs.yml' # option
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
