name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build site
        run: |
          mkdocs build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
