name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |
          mkdocs build
      - name: Print
        run: |
          ls -la
          cd site
          ls -la
          cd ..
          cd ..
          ls -la
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
